language: android

sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support

script:
  #- "./gradlew assembleRelease"
