language: android

sudo: false

before_script:
  - emulator -avd test -no-skin -no-audio -no-window &

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support

script:
  #- "./gradlew assembleRelease"
