#!/bin/bash

API_KEY=$1
USER_KEY=$2
ORIGINAL_FILENAME="app-release.apk" # github 自动编译测试包生成的 apk 名字
PACKAGE_DIR="app/build/outputs/apk/release" # 安装包位置

# App 的 bundleId 或 包名
BUNDLE_ID="com.hgo.planassistant"

package_path="${PACKAGE_DIR}/${ORIGINAL_FILENAME}"
UPLOAD_URL="https://www.pgyer.com/apiv1/app/upload"

# Upload package
echo 'Uploading...'
echo '✈ -------------------------------------------- ✈'

response=$(curl -F "file=@${package_path}" \
-F "uKey=${USER_KEY}" \
-F "_api_key=${API_KEY}" \
-F "updateDescription=$(git log -1 --pretty=format:"%s")" \
${UPLOAD_URL}
)
echo $response;
